"use client";

import { motion } from "framer-motion";
import type { Metadata } from "next";

const LAST_UPDATED = "15 March 2026";

const sections = [
    {
        id: "interpretation",
        title: "Interpretation & Definitions",
        content: [
            {
                heading: "Interpretation",
                body: `The words of which the initial letter is capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
            },
            {
                heading: "Definitions",
                body: null,
                definitions: [
                    { term: "Company", def: `Referred to as "We", "Us" or "Our" — refers to Autisync, a creative digital agency operating in the United Kingdom.` },
                    { term: "Website", def: `Refers to the Autisync website, accessible from https://www.autisync.com` },
                    { term: "Service", def: `Refers to the Website and any digital services provided by Autisync.` },
                    { term: "You", def: `The individual accessing or using the Service, or the company on behalf of which such individual is accessing or using the Service.` },
                    { term: "Personal Data", def: `Any information that relates to an identified or identifiable individual.` },
                    { term: "Usage Data", def: `Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.` },
                    { term: "Cookies", def: `Small files placed on Your device by the Website, containing browsing information used to improve your experience.` },
                    { term: "Service Provider", def: `Any natural or legal person who processes data on behalf of the Company, including third-party analytics and communication tools.` },
                    { term: "Account", def: `A unique account created for You to access our Service or parts of our Service, where applicable.` },
                    { term: "Country", def: `United Kingdom` },
                ],
            },
        ],
    },
    {
        id: "data-collected",
        title: "Data We Collect",
        content: [
            {
                heading: "Information you provide directly",
                body: `We collect personal information you voluntarily submit through the following channels on our website:`,
                list: [
                    `Contact form — your name, email address, phone number, and message content.`,
                    `Service questionnaires — detailed information about your brand, project goals, budget, technology preferences, audience, and other business context required to scope and deliver our services. This includes the Graphic Design, App/Website, Social Media, Technical Support, E-Commerce, and Email Marketing questionnaires.`,
                ],
            },
            {
                heading: "Usage Data",
                body: `We automatically collect Usage Data when you visit our Website. This may include your IP address, browser type and version, the pages you visit, the time and date of your visit, time spent on pages, and other diagnostic information. When you access the Service via a mobile device, we may additionally collect your device type, mobile operating system, and unique device identifiers.`,
            },
            {
                heading: "Analytics",
                body: `We use third-party analytics tools (such as Google Analytics or equivalent services) to understand how visitors interact with our Website. These tools may collect data about your browser, location, and browsing behaviour in aggregate form. Analytics data helps us improve the performance, content, and user experience of our Website.`,
            },
            {
                heading: "Cookies & Tracking Technologies",
                body: `We use Cookies and similar tracking technologies to track activity on our Service and store certain preferences. The technologies we use include browser cookies, web beacons, pixel tags, and scripts. You can instruct your browser to refuse all cookies or to alert you when a cookie is sent; however, some parts of our Service may not function correctly if cookies are disabled.`,
                list: [
                    `Essential / Session Cookies — required for the Website to function correctly, including navigation and security.`,
                    `Analytics Cookies — used to understand traffic and usage patterns (e.g. Google Analytics).`,
                    `Preference / Functionality Cookies — remember your settings and choices across visits.`,
                    `Cookie Acceptance Cookies — record whether you have accepted our cookie policy.`,
                ],
            },
        ],
    },
    {
        id: "how-we-use",
        title: "How We Use Your Data",
        content: [
            {
                heading: null,
                body: `We use the personal data we collect for the following purposes:`,
                list: [
                    `To respond to enquiries submitted via our contact form.`,
                    `To review and act on questionnaire submissions in order to prepare project proposals, scoping documents, and service agreements.`,
                    `To provide, operate, and improve our Website and services.`,
                    `To monitor and analyse usage patterns and improve the performance and content of our Website.`,
                    `To contact you by email, phone, or other electronic means regarding your enquiry, a project you have engaged us for, or relevant updates about our services.`,
                    `To send you news, offers, or information about services similar to those you have enquired about — unless you opt out.`,
                    `To comply with legal obligations and protect our legal rights.`,
                    `To evaluate or conduct business transfers such as mergers or acquisitions, where user data may be among the assets involved.`,
                ],
            },
        ],
    },
    {
        id: "sharing",
        title: "Sharing Your Personal Data",
        content: [
            {
                heading: null,
                body: `We do not sell your personal data. We may share your information in the following limited circumstances:`,
                list: [
                    `With Service Providers — third-party companies that help us deliver our services, such as email delivery platforms (e.g. for sending questionnaire submissions to our team), analytics providers, and hosting infrastructure. These providers are contractually required to protect your data.`,
                    `With Affiliates — entities under common control with Autisync, who are bound by the same data protection obligations.`,
                    `For legal compliance — when required by law or in response to valid requests from public authorities (e.g. courts or government agencies).`,
                    `For business transfers — in connection with a merger, sale, or acquisition of Autisync or its assets.`,
                    `With your consent — for any other purpose explicitly agreed to by you.`,
                ],
            },
        ],
    },
    {
        id: "retention",
        title: "Data Retention",
        content: [
            {
                heading: null,
                body: `We retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, or as required by law. Questionnaire and contact form data is retained for as long as is needed to manage the corresponding client relationship or enquiry. Usage Data and analytics data are generally retained for shorter periods unless required for security, performance analysis, or legal purposes. You may request deletion of your data at any time (see "Your Rights" below).`,
            },
        ],
    },
    {
        id: "transfer",
        title: "Transfer of Your Data",
        content: [
            {
                heading: null,
                body: `Your information may be processed at our operating offices and at the locations of our third-party Service Providers, which may be outside the United Kingdom. By using our Service and submitting information, you consent to this transfer. We take all reasonably necessary steps to ensure your data is handled securely and in accordance with this Privacy Policy. No transfer will occur unless adequate data protection controls are in place.`,
            },
        ],
    },
    {
        id: "your-rights",
        title: "Your Rights",
        content: [
            {
                heading: null,
                body: `Under applicable data protection law (including UK GDPR), you have the following rights regarding your personal data:`,
                list: [
                    `Right of access — you may request a copy of the personal data we hold about you.`,
                    `Right to rectification — you may ask us to correct inaccurate or incomplete data.`,
                    `Right to erasure — you may request that we delete your personal data, subject to legal obligations.`,
                    `Right to restrict processing — you may ask us to limit how we use your data in certain circumstances.`,
                    `Right to data portability — you may request your data in a commonly used, machine-readable format.`,
                    `Right to object — you may object to processing based on legitimate interests or for direct marketing purposes.`,
                    `Right to withdraw consent — where we rely on your consent to process data, you may withdraw it at any time.`,
                ],
            },
            {
                heading: null,
                body: `To exercise any of these rights, please contact us at info@autisync.com. We will respond within 30 days. You also have the right to lodge a complaint with the Information Commissioner's Office (ICO) in the UK at https://ico.org.uk.`,
            },
        ],
    },
    {
        id: "security",
        title: "Security of Your Data",
        content: [
            {
                heading: null,
                body: `The security of your Personal Data is important to us. We use commercially reasonable technical and organisational measures to protect your data, including encrypted data transmission (HTTPS) and access controls. However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security and encourage you to use strong, unique passwords and to contact us immediately if you suspect any unauthorised access.`,
            },
        ],
    },
    {
        id: "childrens",
        title: "Children's Privacy",
        content: [
            {
                heading: null,
                body: `Our Service is not directed at anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. If you are a parent or guardian and believe your child has submitted personal data to us, please contact us at info@autisync.com and we will promptly remove such information from our records.`,
            },
        ],
    },
    {
        id: "third-party",
        title: "Links to Other Websites",
        content: [
            {
                heading: null,
                body: `Our Website may contain links to third-party websites not operated by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites. We strongly advise you to review the privacy policy of every site you visit.`,
            },
        ],
    },
    {
        id: "changes",
        title: "Changes to This Policy",
        content: [
            {
                heading: null,
                body: `We may update this Privacy Policy from time to time. When we do, we will revise the "Last updated" date at the top of this page. For significant changes, we will notify you by email or by a prominent notice on our Website prior to the change becoming effective. We encourage you to review this Privacy Policy periodically.`,
            },
        ],
    },
    {
        id: "contact",
        title: "Contact Us",
        content: [
            {
                heading: null,
                body: `If you have any questions, concerns, or requests regarding this Privacy Policy or the way we handle your personal data, please contact us:`,
                list: [
                    `Email: info@autisync.com`,
                    `WhatsApp: +44 788 331 7646`,
                    `Website: https://www.autisync.com`,
                ],
            },
        ],
    },
];

export default function PrivacyPolicyPage() {
    return (
        <main className="min-h-screen bg-gray-50">
            {/* ── Hero ─────────────────────────────────────────────────────────── */}
            <section className="relative overflow-hidden bg-gradient-to-b from-black via-black/90 to-black/80">
                <div
                    className="absolute inset-0 bg-center bg-cover opacity-30"
                    style={{
                        backgroundImage:
                            "url('https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2')",
                    }}
                />
                <div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/80 to-black/95" />

                {/* Gold accent line */}
                <div
                    className="absolute bottom-0 left-0 right-0 h-px"
                    style={{ background: "linear-gradient(to right, transparent, #b98b2f, transparent)" }}
                />

                <div className="relative px-4 pt-28 pb-16 mx-auto max-w-4xl text-center sm:px-6 lg:px-8">
                    <motion.p
                        initial={{ opacity: 0, y: 12 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5 }}
                        className="mb-3 text-xs font-semibold uppercase tracking-[0.35em] text-[#b98b2f]"
                    >
                        Legal
                    </motion.p>
                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.55, delay: 0.05 }}
                        className="text-4xl font-bold tracking-tight text-white sm:text-5xl"
                    >
                        Privacy Policy
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0, y: 16 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.55, delay: 0.12 }}
                        className="mt-4 text-sm text-gray-400"
                    >
                        Last updated: {LAST_UPDATED}
                    </motion.p>
                    <motion.p
                        initial={{ opacity: 0, y: 16 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6, delay: 0.18 }}
                        className="mt-5 mx-auto max-w-2xl text-base text-gray-300 leading-relaxed"
                    >
                        This Privacy Policy describes how Autisync collects, uses, and protects
                        your information when you use our website, submit enquiries or questionnaires,
                        or engage with our services.
                    </motion.p>
                </div>
            </section>

            {/* ── Body ─────────────────────────────────────────────────────────── */}
            <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
                <div className="lg:grid lg:grid-cols-[220px_1fr] lg:gap-12">

                    {/* Sticky sidebar TOC — desktop only */}
                    <aside className="hidden lg:block">
                        <div className="sticky top-24">
                            <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.25em] text-[#b98b2f]">
                                Contents
                            </p>
                            <nav className="space-y-1">
                                {sections.map((s) => (
                                    <a
                                        key={s.id}
                                        href={`#${s.id}`}
                                        className="block rounded-md px-3 py-1.5 text-xs text-gray-500 transition-colors hover:bg-[#b98b2f]/8 hover:text-[#b98b2f]"
                                    >
                                        {s.title}
                                    </a>
                                ))}
                            </nav>
                        </div>
                    </aside>

                    {/* Main content */}
                    <div className="space-y-12">
                        {/* Intro blurb */}
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5 }}
                            className="rounded-xl border border-[#b98b2f]/20 bg-[#b98b2f]/5 px-6 py-5"
                        >
                            <p className="text-sm leading-relaxed text-gray-700">
                                By using our Website or submitting any form, you agree to the collection
                                and use of information in accordance with this Privacy Policy. We are committed
                                to being transparent about how we handle your data and to protecting your privacy
                                in compliance with UK GDPR and applicable data protection legislation.
                            </p>
                        </motion.div>

                        {sections.map((section, sIdx) => (
                            <motion.section
                                key={section.id}
                                id={section.id}
                                initial={{ opacity: 0, y: 24 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true, margin: "-60px" }}
                                transition={{ duration: 0.45, delay: sIdx * 0.03 }}
                                className="scroll-mt-24"
                            >
                                {/* Section title */}
                                <div className="mb-5 flex items-center gap-3">
                                    <div
                                        className="h-5 w-1 flex-shrink-0 rounded-full"
                                        style={{ background: "linear-gradient(to bottom, #b98b2f, #7a5a1d)" }}
                                    />
                                    <h2 className="text-lg font-semibold text-gray-900">{section.title}</h2>
                                </div>

                                <div className="space-y-5 pl-4">
                                    {section.content.map((block, bIdx) => (
                                        <div key={bIdx}>
                                            {block.heading && (
                                                <h3 className="mb-2 text-sm font-semibold text-gray-800">
                                                    {block.heading}
                                                </h3>
                                            )}

                                            {block.body && (
                                                <p className="text-sm leading-relaxed text-gray-600">{block.body}</p>
                                            )}

                                            {/* Definitions list */}
                                            {"definitions" in block && block.definitions && (
                                                <dl className="mt-3 space-y-3">
                                                    {block.definitions.map((d) => (
                                                        <div key={d.term} className="rounded-lg border border-gray-100 bg-white px-4 py-3 shadow-sm">
                                                            <dt className="text-xs font-semibold text-[#b98b2f]">{d.term}</dt>
                                                            <dd className="mt-0.5 text-sm text-gray-600">{d.def}</dd>
                                                        </div>
                                                    ))}
                                                </dl>
                                            )}

                                            {/* Bullet list */}
                                            {"list" in block && block.list && (
                                                <ul className="mt-3 space-y-2">
                                                    {block.list.map((item, i) => (
                                                        <li key={i} className="flex gap-2.5 text-sm text-gray-600">
                              <span
                                  className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full"
                                  style={{ backgroundColor: "#b98b2f" }}
                              />
                                                            {item}
                                                        </li>
                                                    ))}
                                                </ul>
                                            )}
                                        </div>
                                    ))}
                                </div>

                                {/* Divider */}
                                {sIdx < sections.length - 1 && (
                                    <div className="mt-10 h-px bg-gray-100" />
                                )}
                            </motion.section>
                        ))}

                        {/* Footer note */}
                        <div className="rounded-xl border border-gray-200 bg-white px-6 py-5 text-center shadow-sm">
                            <p className="text-xs text-gray-400">
                                © {new Date().getFullYear()} Autisync. All rights reserved.{" "}
                                <br className="sm:hidden" />
                                Questions? Email us at{" "}
                                <a href="mailto:info@autisync.com" className="text-[#b98b2f] hover:underline">
                                    info@autisync.com
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}